###########
# site.title

title:    'nicole voec'



#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

collections:
- portfolio